base: 'https://typo3-impexp-80617.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
    fallbackType: fallback
    fallbacks: '0'
  -
    title: French
    enabled: true
    languageId: 2
    base: /fr/
    locale: fr_FR.UTF-8
    navigationTitle: Francaise
    flag: fr
    hreflang: ''
    websiteTitle: ''
    fallbackType: fallback
    fallbacks: '0'
  -
    title: Danish
    enabled: true
    locale: da_DK
    hreflang: ''
    base: /dk/
    websiteTitle: ''
    navigationTitle: Dansk
    fallbackType: fallback
    fallbacks: '0'
    flag: im
    languageId: 3
rootPageId: 1
websiteTitle: 'TYPO3 SVG crop (issue 80617)'
