base: 'https://typo3-core-bugreproduce-base.ddev.site/'
dependencies:
  - bootstrap-package/content-elements
  - bootstrap-package/full
  - typo3/felogin
  - typo3/styleguide
  - typo3/seo-sitemap
  - typo3/indexed-search
  - typo3/redirects
  - typo3/fluid-styled-content-css
  - typo3/form
  - typo3/fluid-styled-content
errorHandling:
  -
    errorCode: 403
    errorHandler: LoginRedirect
    loginRedirectTarget: 't3://page?uid=2736'
    loginRedirectParameter: return_url
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: Dütsch
    enabled: true
    locale: de_AT
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: global
    languageId: 22
myNewField: customfield
rootPageId: 1
websiteTitle: 'New TYPO3 website'
settings:
  redirects:
    autoCreateRedirects: 0
